2017 05 test multiselect library
liqd/a4-advocate-europe pull request #39
Opened 2017-04-26 11:23 UTC by MagdaN

added multiselect with template tag, but we can remove the template tag if this better doable with crispy forms

2017-04-27 05:52 UTC, slomo requested changes
I think we should definitly fix the issues with organisation type.

2017-04-27 05:52 UTC, slomo commented on apps/ideas/models/abstracts/applicant_section.py
> +    organisation_status = MultiSelectField(max_length=255,
This shouldn't be a multi select. You can only have one organisation status.

2017-04-27 05:52 UTC, slomo commented on apps/ideas/templatetags/idea_tags.py
> +    return field.field.widget.__class__.__name__ == 'CheckboxSelectMultiple'
What is called field in the definition is already the widget, or isn't it?

2017-05-02 10:24 UTC, slomo approved these changes

2017-05-02 15:30 UTC, fuzzylogic2000 approved these changes
Seems to work fine, but a help text (chose 1 or 2)  for the idea topics would be good.

2017-05-03 07:46 UTC, slomo commented
@fuzzylogic2000 Added help texts

2017-05-03 07:50 UTC, merged